(function () {
  "use strict";

  // Dados extraídos de https://unidadepopular.org.br/eleicoes (2026-08-31).
  // slug = mesmo slug usado em unidadepopular.org.br/eleicoes/<slug>, também
  // usado para achar a moldura em assets/overlays/<slug>.png e para a URL
  // desta página (campanha-up.github.io/<slug>).
  var CANDIDATURAS = [
    { slug: "samara-martins", nome: "Samara Martins", cargo: "presidente", cargoRotulo: "Presidente", uf: null, estado: "Nacional" },
    { slug: "lenilda-luna", nome: "Lenilda Luna", cargo: "governador", cargoRotulo: "Governador(a)", uf: "AL", estado: "Alagoas" },
    { slug: "aroldo-felix", nome: "Aroldo Félix", cargo: "governador", cargoRotulo: "Governador(a)", uf: "BA", estado: "Bahia" },
    { slug: "serley-leal", nome: "Serley Leal", cargo: "governador", cargoRotulo: "Governador(a)", uf: "CE", estado: "Ceará" },
    { slug: "professora-samara-mineiro", nome: "Professora Samara Mineiro", cargo: "governador", cargoRotulo: "Governador(a)", uf: "DF", estado: "Distrito Federal" },
    { slug: "rafael-demuner", nome: "Rafael Demuner", cargo: "governador", cargoRotulo: "Governador(a)", uf: "ES", estado: "Espírito Santo" },
    { slug: "luciana-amorim", nome: "Luciana Amorim", cargo: "governador", cargoRotulo: "Governador(a)", uf: "GO", estado: "Goiás" },
    { slug: "indira-xavier", nome: "Indira Xavier", cargo: "governador", cargoRotulo: "Governador(a)", uf: "MG", estado: "Minas Gerais" },
    { slug: "gal-leite", nome: "Gal Leite", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PA", estado: "Pará" },
    { slug: "yuri-ezequiel", nome: "Yuri Ezequiel", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PB", estado: "Paraíba" },
    { slug: "tayna-miessa", nome: "Tayna Miessa", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PR", estado: "Paraná" },
    { slug: "professora-camila", nome: "Professora Camila", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PE", estado: "Pernambuco" },
    { slug: "santiago-belizario", nome: "Santiago Belizário", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PI", estado: "Piauí" },
    { slug: "juliete", nome: "Juliete", cargo: "governador", cargoRotulo: "Governador(a)", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "arinalda-mlb", nome: "Arinalda do MLB", cargo: "governador", cargoRotulo: "Governador(a)", uf: "RN", estado: "Rio Grande do Norte" },
    { slug: "priscila-voigt", nome: "Priscila Voigt", cargo: "governador", cargoRotulo: "Governador(a)", uf: "RS", estado: "Rio Grande do Sul" },
    { slug: "lais-chaud", nome: "Laís Chaud", cargo: "governador", cargoRotulo: "Governador(a)", uf: "SC", estado: "Santa Catarina" },
    { slug: "vivian-mendes", nome: "Vivian Mendes", cargo: "governador", cargoRotulo: "Governador(a)", uf: "SP", estado: "São Paulo" },
    { slug: "alexandre-fleming", nome: "Alexandre Fleming", cargo: "senador", cargoRotulo: "Senador(a)", uf: "AL", estado: "Alagoas" },
    { slug: "gregorio-gould", nome: "Gregório Gould", cargo: "senador", cargoRotulo: "Senador(a)", uf: "BA", estado: "Bahia" },
    { slug: "catarina-matos", nome: "Catarina Matos", cargo: "senador", cargoRotulo: "Senador(a)", uf: "CE", estado: "Ceará" },
    { slug: "professor-guilherme-amorim", nome: "Professor Guilherme Amorim", cargo: "senador", cargoRotulo: "Senador(a)", uf: "DF", estado: "Distrito Federal" },
    { slug: "guilherme-darques", nome: "Guilherme Darques", cargo: "senador", cargoRotulo: "Senador(a)", uf: "GO", estado: "Goiás" },
    { slug: "ana-luiza-do-mlb", nome: "Ana Luiza do MLB", cargo: "senador", cargoRotulo: "Senador(a)", uf: "MG", estado: "Minas Gerais" },
    { slug: "fidelis-alcantara", nome: "Fidélis Alcântara", cargo: "senador", cargoRotulo: "Senador(a)", uf: "MG", estado: "Minas Gerais" },
    { slug: "fernanda-lopes", nome: "Fernanda Lopes", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PA", estado: "Pará" },
    { slug: "joao-batista", nome: "João Batista", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PB", estado: "Paraíba" },
    { slug: "rosilene-santana", nome: "Rosilene Santana", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PB", estado: "Paraíba" },
    { slug: "joaquim-maciel", nome: "Joaquim do MLB", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PR", estado: "Paraná" },
    { slug: "gorett-bitu", nome: "Gorett Bitu", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PE", estado: "Pernambuco" },
    { slug: "samuel-timoteo", nome: "Samuel Timoteo", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PE", estado: "Pernambuco" },
    { slug: "pedro-laurentino", nome: "Pedro Laurentino", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PI", estado: "Piauí" },
    { slug: "michelly-xavier", nome: "Michelly Xavier", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "vinicius-benevides", nome: "Vinícius Benevides", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "professor-guilherme-mosca", nome: "Professor Guilherme Mosca", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RN", estado: "Rio Grande do Norte" },
    { slug: "luciano-schafer", nome: "Luciano Schafer", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RS", estado: "Rio Grande do Sul" },
    { slug: "tania-peres", nome: "Tânia Peres", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RS", estado: "Rio Grande do Sul" },
    { slug: "ana-lucia", nome: "Ana Lucia da Silveira Machado", cargo: "senador", cargoRotulo: "Senador(a)", uf: "SC", estado: "Santa Catarina" },
    { slug: "marlene-soccas", nome: "Marlene Soccas", cargo: "senador", cargoRotulo: "Senador(a)", uf: "SC", estado: "Santa Catarina" },
    { slug: "maira-de-souza", nome: "Maíra de Souza", cargo: "senador", cargoRotulo: "Senador(a)", uf: "SP", estado: "São Paulo" },
    { slug: "marcio-alves", nome: "Marcio Alves", cargo: "senador", cargoRotulo: "Senador(a)", uf: "SP", estado: "São Paulo" },
    { slug: "charles-pereira", nome: "Charles Pereira", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "AL", estado: "Alagoas" },
    { slug: "lili-anjos", nome: "Lili Anjos", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "AL", estado: "Alagoas" },
    { slug: "ana-roque", nome: "Ana Roque", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "AM", estado: "Amazonas" },
    { slug: "joao-lima", nome: "João Lima", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "AM", estado: "Amazonas" },
    { slug: "giovana-ferreira", nome: "Giovana Ferreira", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "BA", estado: "Bahia" },
    { slug: "guizin", nome: "Guizin", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "BA", estado: "Bahia" },
    { slug: "haroldo-neto", nome: "Haroldo Neto", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "CE", estado: "Ceará" },
    { slug: "lucas-monte", nome: "Lucas Monte", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "CE", estado: "Ceará" },
    { slug: "sued-carvalho", nome: "Sued Carvalho", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "CE", estado: "Ceará" },
    { slug: "durval", nome: "Durval", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "DF", estado: "Distrito Federal" },
    { slug: "milena-do-mlb", nome: "Milena do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "DF", estado: "Distrito Federal" },
    { slug: "gabriel-costa", nome: "Gabriel Costa", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "ES", estado: "Espírito Santo" },
    { slug: "luisa-kirchmayer", nome: "Luisa Kirchmayer", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "ES", estado: "Espírito Santo" },
    { slug: "emily-eloa", nome: "Emily Eloá", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "GO", estado: "Goiás" },
    { slug: "fausto-andre", nome: "Fausto André", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "GO", estado: "Goiás" },
    { slug: "afonso-sodre", nome: "Afonso Sodré", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MA", estado: "Maranhão" },
    { slug: "agata-trebi", nome: "Ágata Trebi", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MA", estado: "Maranhão" },
    { slug: "edinho-do-mlb", nome: "Edinho do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MG", estado: "Minas Gerais" },
    { slug: "helena-nara", nome: "Helena Nara", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MG", estado: "Minas Gerais" },
    { slug: "rafael-fumero", nome: "Rafael Fumero", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MG", estado: "Minas Gerais" },
    { slug: "bruna-freire", nome: "Bruna Freire", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PA", estado: "Pará" },
    { slug: "henrique-maciel", nome: "Henrique Maciel", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PA", estado: "Pará" },
    { slug: "isabele-do-correnteza", nome: "Isabele do Correnteza", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PB", estado: "Paraíba" },
    { slug: "jonas-souza", nome: "Jonas Souza", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PB", estado: "Paraíba" },
    { slug: "giovanny-godoi", nome: "Giovanny Godoi", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PR", estado: "Paraná" },
    { slug: "julia-de-souza-marinho", nome: "Julia Marinho", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PR", estado: "Paraná" },
    { slug: "madu-silva", nome: "Madu Silva", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PE", estado: "Pernambuco" },
    { slug: "matheus-do-mlb", nome: "Matheus do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PE", estado: "Pernambuco" },
    { slug: "augusto-ferreira", nome: "Augusto Ferreira", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PI", estado: "Piauí" },
    { slug: "dara-neto", nome: "Dara Neto", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PI", estado: "Piauí" },
    { slug: "esteban-crescente", nome: "Esteban Crescente", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "petala", nome: "Pétala", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "bia-do-mlb", nome: "Bia do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RN", estado: "Rio Grande do Norte" },
    { slug: "victor-hugo", nome: "Victor Hugo", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RN", estado: "Rio Grande do Norte" },
    { slug: "bruno-do-mlb", nome: "Bruno do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RS", estado: "Rio Grande do Sul" },
    { slug: "gustavo-ramos", nome: "Gustavo Ramos", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RS", estado: "Rio Grande do Sul" },
    { slug: "prof-jaque", nome: "Prof Jaque", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RS", estado: "Rio Grande do Sul" },
    { slug: "amanda-wenceslau", nome: "Amanda Wenceslau", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SC", estado: "Santa Catarina" },
    { slug: "andre-drejan", nome: "André Drejan", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SC", estado: "Santa Catarina" },
    { slug: "dany-oliveira", nome: "Dany Oliveira", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo" },
    { slug: "karla-albuquerque", nome: "Karla Albuquerque", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo" },
    { slug: "matheus-morais", nome: "Matheus Morais", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo" },
    { slug: "ricardo-senese", nome: "Ricardo Senese", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo" },
    { slug: "thais-gasparinj", nome: "Thais Gasparini", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo" },
    { slug: "bruna-makida", nome: "Bruna Makida", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SE", estado: "Sergipe" },
    { slug: "mateus-henriques", nome: "Mateus Henriques", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SE", estado: "Sergipe" },
    { slug: "daniel-calisto", nome: "Daniel Calisto", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "AL", estado: "Alagoas" },
    { slug: "professora-maria-jose", nome: "Professora Maria José", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "AL", estado: "Alagoas" },
    { slug: "louise-ferreira", nome: "Louise Ferreira", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "BA", estado: "Bahia" },
    { slug: "willian-santos", nome: "Willian Santos", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "BA", estado: "Bahia" },
    { slug: "dianne-glebia", nome: "Dianne Glebia", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "CE", estado: "Ceará" },
    { slug: "otavio-miranda", nome: "Otávio Miranda", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "CE", estado: "Ceará" },
    { slug: "barbara-calista", nome: "Bárbara Calista", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "DF", estado: "Distrito Federal" },
    { slug: "christian-sena", nome: "Christian Rodrigues Sena", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "DF", estado: "Distrito Federal" },
    { slug: "larissa-moura", nome: "Larissa Moura", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "GO", estado: "Goiás" },
    { slug: "prof-pedro-augusto", nome: "Prof. Pedro Augusto", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "GO", estado: "Goiás" },
    { slug: "daniel-tito", nome: "Daniel Tito", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "MG", estado: "Minas Gerais" },
    { slug: "candidatura-coletiva-contra-mineracao", nome: "Iris Raquel Contra a Mineração", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "MG", estado: "Minas Gerais" },
    { slug: "marcos-jobson", nome: "Marcos Jobson", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PA", estado: "Pará" },
    { slug: "maria-santos", nome: "Maria Santos", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PA", estado: "Pará" },
    { slug: "jozivan-antero", nome: "Jozivan Antero", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PB", estado: "Paraíba" },
    { slug: "prof-cleber", nome: "Prof. Cleber", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PB", estado: "Paraíba" },
    { slug: "vitoria-ohara", nome: "Vitoria Ohara", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PB", estado: "Paraíba" },
    { slug: "juliane-mendes", nome: "Juliane Mendes", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PR", estado: "Paraná" },
    { slug: "lohan-cota", nome: "Lohan Cota", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PR", estado: "Paraná" },
    { slug: "jessica-nathalia", nome: "Jéssica Nathália", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PE", estado: "Pernambuco" },
    { slug: "paulo-fernando", nome: "Paulo Fernando", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PE", estado: "Pernambuco" },
    { slug: "bianca-rubim", nome: "Bianca Rubim", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "dulce", nome: "Dulce", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "eunice-do-mlb", nome: "Eunice do MLB", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "henderson", nome: "Henderson", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "monique-zuma", nome: "Monique Zuma", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "ruan-vidal", nome: "Ruan Vidal", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro" },
    { slug: "chapa-coletiva-fnr", nome: "Chapa Coletiva FNR", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RN", estado: "Rio Grande do Norte" },
    { slug: "milenne-barbosa", nome: "Milenne Barbosa", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RN", estado: "Rio Grande do Norte" },
    { slug: "everaldo", nome: "Everaldo Oliveira", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RS", estado: "Rio Grande do Sul" },
    { slug: "samara", nome: "Samara Garcia", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RS", estado: "Rio Grande do Sul" },
    { slug: "frente-operaria", nome: "Frente Operaria", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "SP", estado: "São Paulo" },
    { slug: "julia-cachos", nome: "Julia Cachos", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "SP", estado: "São Paulo" },
    { slug: "giovanni-oliveira", nome: "Giovanni Oliveira", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "SE", estado: "Sergipe" },
    { slug: "rose-mlb", nome: "Rose do MLB", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "SE", estado: "Sergipe" }
  ];

  // Ordem de exibição dos cargos nos seletores (não é ordem alfabética).
  var ORDEM_CARGOS = ["presidente", "governador", "senador", "deputado-federal", "deputado-estadual"];

  window.CANDIDATURAS = CANDIDATURAS;
  window.ORDEM_CARGOS = ORDEM_CARGOS;
  window.CANDIDATURA_PADRAO = "samara-martins";
})();
