(function () {
  "use strict";

  // Dados extraídos de https://unidadepopular.org.br/eleicoes (2026-08-31).
  // slug = mesmo slug usado em unidadepopular.org.br/eleicoes/<slug>, também
  // usado para achar a moldura em assets/overlays/<slug>.png e para a URL
  // desta página (campanha-up.github.io/<slug>).
  var CANDIDATURAS = [
    { slug: "samara-martins", nome: "Samara Martins", cargo: "presidente", cargoRotulo: "Presidente", uf: null, estado: "Nacional", genero: "f", nomeArco: "Samara" },
    { slug: "lenilda-luna", nome: "Lenilda Luna", cargo: "governador", cargoRotulo: "Governador(a)", uf: "AL", estado: "Alagoas", genero: "f", nomeArco: "Lenilda Luna" },
    { slug: "aroldo-felix", nome: "Aroldo Félix", cargo: "governador", cargoRotulo: "Governador(a)", uf: "BA", estado: "Bahia", genero: "m", nomeArco: "Aroldo" },
    { slug: "serley-leal", nome: "Serley Leal", cargo: "governador", cargoRotulo: "Governador(a)", uf: "CE", estado: "Ceará", genero: "m", nomeArco: "Serley Leal" },
    { slug: "professora-samara-mineiro", nome: "Professora Samara Mineiro", cargo: "governador", cargoRotulo: "Governador(a)", uf: "DF", estado: "Distrito Federal", genero: "f", nomeArco: "Professora Samara Mineiro" },
    { slug: "rafael-demuner", nome: "Rafael Demuner", cargo: "governador", cargoRotulo: "Governador(a)", uf: "ES", estado: "Espírito Santo", genero: "m", nomeArco: "Rafael" },
    { slug: "luciana-amorim", nome: "Luciana Amorim", cargo: "governador", cargoRotulo: "Governador(a)", uf: "GO", estado: "Goiás", genero: "f", nomeArco: "Luciana" },
    { slug: "indira-xavier", nome: "Indira Xavier", cargo: "governador", cargoRotulo: "Governador(a)", uf: "MG", estado: "Minas Gerais", genero: "f", nomeArco: "Indira Xavier" },
    { slug: "gal-leite", nome: "Gal Leite", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PA", estado: "Pará", genero: "f", nomeArco: "Gal Leite" },
    { slug: "yuri-ezequiel", nome: "Yuri Ezequiel", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PB", estado: "Paraíba", genero: "m", nomeArco: "Yuri Ezequiel" },
    { slug: "tayna-miessa", nome: "Tayna Miessa", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PR", estado: "Paraná", genero: "f", nomeArco: "Tayna Miessa" },
    { slug: "professora-camila", nome: "Professora Camila", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PE", estado: "Pernambuco", genero: "f", nomeArco: "Professora Camila" },
    { slug: "santiago-belizario", nome: "Santiago Belizário", cargo: "governador", cargoRotulo: "Governador(a)", uf: "PI", estado: "Piauí", genero: "m", nomeArco: "Santiago" },
    { slug: "juliete", nome: "Juliete Pantoja", cargo: "governador", cargoRotulo: "Governador(a)", uf: "RJ", estado: "Rio de Janeiro", genero: "f", nomeArco: "Juliete Pantoja" },
    { slug: "arinalda-mlb", nome: "Arinalda do MLB", cargo: "governador", cargoRotulo: "Governador(a)", uf: "RN", estado: "Rio Grande do Norte", genero: "f", nomeArco: "Arinalda do MLB" },
    { slug: "priscila-voigt", nome: "Priscila Voigt", cargo: "governador", cargoRotulo: "Governador(a)", uf: "RS", estado: "Rio Grande do Sul", genero: "f", nomeArco: "Priscila Voigt" },
    { slug: "lais-chaud", nome: "Laís Chaud", cargo: "governador", cargoRotulo: "Governador(a)", uf: "SC", estado: "Santa Catarina", genero: "f", nomeArco: "Laís Chaud" },
    { slug: "vivian-mendes", nome: "Vivian Mendes", cargo: "governador", cargoRotulo: "Governador(a)", uf: "SP", estado: "São Paulo", genero: "f", nomeArco: "Vivian Mendes" },
    { slug: "alexandre-fleming", nome: "Alexandre Fleming", cargo: "senador", cargoRotulo: "Senador(a)", uf: "AL", estado: "Alagoas", genero: "m", nomeArco: "Alexandre", numero: "800" },
    { slug: "gregorio-gould", nome: "Gregório Gould", cargo: "senador", cargoRotulo: "Senador(a)", uf: "BA", estado: "Bahia", genero: "m", nomeArco: "Gregório", numero: "800" },
    { slug: "catarina-matos", nome: "Catarina Matos", cargo: "senador", cargoRotulo: "Senador(a)", uf: "CE", estado: "Ceará", genero: "f", nomeArco: "Catarina", numero: "800" },
    { slug: "professor-guilherme-amorim", nome: "Professor Guilherme Amorim", cargo: "senador", cargoRotulo: "Senador(a)", uf: "DF", estado: "Distrito Federal", genero: "m", nomeArco: "Professor Guilherme", numero: "800" },
    { slug: "guilherme-darques", nome: "Guilherme Darques", cargo: "senador", cargoRotulo: "Senador(a)", uf: "GO", estado: "Goiás", genero: "m", nomeArco: "Guilherme", numero: "800" },
    { slug: "ana-luiza-do-mlb", nome: "Ana Luiza do MLB", cargo: "senador", cargoRotulo: "Senador(a)", uf: "MG", estado: "Minas Gerais", genero: "f", nomeArco: "Ana Luiza do MLB", numero: "808" },
    { slug: "fidelis-alcantara", nome: "Fidélis Alcântara", cargo: "senador", cargoRotulo: "Senador(a)", uf: "MG", estado: "Minas Gerais", genero: "m", nomeArco: "Fidélis", numero: "800" },
    { slug: "fernanda-lopes", nome: "Fernanda Lopes", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PA", estado: "Pará", genero: "f", nomeArco: "Fernanda", numero: "800" },
    { slug: "joao-batista", nome: "João Batista", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PB", estado: "Paraíba", genero: "m", nomeArco: "João Batista", numero: "801" },
    { slug: "rosilene-santana", nome: "Rosilene Santana", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PB", estado: "Paraíba", genero: "f", nomeArco: "Rosilene", numero: "800" },
    { slug: "joaquim-maciel", nome: "Joaquim do MLB", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PR", estado: "Paraná", genero: "m", nomeArco: "Joaquim do MLB", numero: "800" },
    { slug: "gorett-bitu", nome: "Gorett Bitu", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PE", estado: "Pernambuco", genero: "f", nomeArco: "Gorett", numero: "801" },
    { slug: "samuel-timoteo", nome: "Samuel Timoteo", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PE", estado: "Pernambuco", genero: "m", nomeArco: "Samuel", numero: "800" },
    { slug: "pedro-laurentino", nome: "Pedro Laurentino", cargo: "senador", cargoRotulo: "Senador(a)", uf: "PI", estado: "Piauí", genero: "m", nomeArco: "Pedro", numero: "800" },
    { slug: "michelly-xavier", nome: "Michelly Xavier", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RJ", estado: "Rio de Janeiro", genero: "f", nomeArco: "Michelly", numero: "800" },
    { slug: "vinicius-benevides", nome: "Vinícius Benevides", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RJ", estado: "Rio de Janeiro", genero: "m", nomeArco: "Vinícius", numero: "808" },
    { slug: "professor-guilherme-mosca", nome: "Professor Guilherme Mosca", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RN", estado: "Rio Grande do Norte", genero: "m", nomeArco: "Professor Guilherme", numero: "800" },
    { slug: "luciano-schafer", nome: "Luciano Schafer", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RS", estado: "Rio Grande do Sul", genero: "m", nomeArco: "Luciano", numero: "800" },
    { slug: "tania-peres", nome: "Tânia Peres", cargo: "senador", cargoRotulo: "Senador(a)", uf: "RS", estado: "Rio Grande do Sul", genero: "f", nomeArco: "Tânia", numero: "808" },
    { slug: "ana-lucia", nome: "Ana Lucia da Silveira Machado", cargo: "senador", cargoRotulo: "Senador(a)", uf: "SC", estado: "Santa Catarina", genero: "f", nomeArco: "Ana Lucia", numero: "800" },
    { slug: "marlene-soccas", nome: "Marlene Soccas", cargo: "senador", cargoRotulo: "Senador(a)", uf: "SC", estado: "Santa Catarina", genero: "f", nomeArco: "Marlene", numero: "808" },
    { slug: "maira-de-souza", nome: "Maíra de Souza", cargo: "senador", cargoRotulo: "Senador(a)", uf: "SP", estado: "São Paulo", genero: "f", nomeArco: "Maíra", numero: "808" },
    { slug: "marcio-alves", nome: "Marcio Alves", cargo: "senador", cargoRotulo: "Senador(a)", uf: "SP", estado: "São Paulo", genero: "m", nomeArco: "Marcio", numero: "800" },
    { slug: "charles-pereira", nome: "Charles Pereira", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "AL", estado: "Alagoas", genero: "m", nomeArco: "Charles Pereira", numero: "8000" },
    { slug: "lili-anjos", nome: "Lili Anjos", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "AL", estado: "Alagoas", genero: "f", nomeArco: "Lili Anjos", numero: "8080" },
    { slug: "ana-roque", nome: "Ana Roque", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "AM", estado: "Amazonas", genero: "f", nomeArco: "Ana Roque", numero: "8000" },
    { slug: "joao-lima", nome: "João Lima", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "AM", estado: "Amazonas", genero: "m", nomeArco: "João Lima", numero: "8080" },
    { slug: "giovana-ferreira", nome: "Giovana Ferreira", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "BA", estado: "Bahia", genero: "f", nomeArco: "Giovana Ferreira", numero: "8080" },
    { slug: "guizin", nome: "Guizin", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "BA", estado: "Bahia", genero: "m", nomeArco: "Guizin", numero: "8000" },
    { slug: "haroldo-neto", nome: "Haroldo Neto", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "CE", estado: "Ceará", genero: "m", nomeArco: "Haroldo Neto", numero: "8000" },
    { slug: "lucas-monte", nome: "Lucas Monte", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "CE", estado: "Ceará", genero: "m", nomeArco: "Lucas Monte", numero: "8088" },
    { slug: "sued-carvalho", nome: "Sued Carvalho", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "CE", estado: "Ceará", genero: "f", nomeArco: "Sued Carvalho", numero: "8080" },
    { slug: "durval", nome: "Durval", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "DF", estado: "Distrito Federal", genero: "m", nomeArco: "Durval", numero: "8080" },
    { slug: "milena-do-mlb", nome: "Milena do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "DF", estado: "Distrito Federal", genero: "f", nomeArco: "Milena do MLB", numero: "8000" },
    { slug: "gabriel-costa", nome: "Gabriel Costa", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "ES", estado: "Espírito Santo", genero: "m", nomeArco: "Gabriel Costa", numero: "8000" },
    { slug: "luisa-kirchmayer", nome: "Luisa Kirchmayer", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "ES", estado: "Espírito Santo", genero: "f", nomeArco: "Luisa Kirchmayer", numero: "8080" },
    { slug: "emily-eloa", nome: "Emily Eloá", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "GO", estado: "Goiás", genero: "f", nomeArco: "Emily Eloá", numero: "8080" },
    { slug: "fausto-andre", nome: "Fausto André", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "GO", estado: "Goiás", genero: "m", nomeArco: "Fausto André", numero: "8000" },
    { slug: "afonso-sodre", nome: "Afonso Sodré", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MA", estado: "Maranhão", genero: "m", nomeArco: "Afonso Sodré", numero: "8000" },
    { slug: "agata-trebi", nome: "Ágata Trebi", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MA", estado: "Maranhão", genero: "f", nomeArco: "Ágata Trebi", numero: "8080" },
    { slug: "edinho-do-mlb", nome: "Edinho do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MG", estado: "Minas Gerais", genero: "m", nomeArco: "Edinho do MLB", numero: "8080" },
    { slug: "helena-nara", nome: "Helena Nara", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MG", estado: "Minas Gerais", genero: "f", nomeArco: "Helena Nara", numero: "8000" },
    { slug: "rafael-fumero", nome: "Rafael Fumero", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "MG", estado: "Minas Gerais", genero: "m", nomeArco: "Rafael Fumero", numero: "8008" },
    { slug: "bruna-freire", nome: "Bruna Freire", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PA", estado: "Pará", genero: "f", nomeArco: "Bruna Freire", numero: "8080" },
    { slug: "henrique-maciel", nome: "Henrique Maciel", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PA", estado: "Pará", genero: "m", nomeArco: "Henrique Maciel", numero: "8000" },
    { slug: "isabele-do-correnteza", nome: "Isabele do Correnteza", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PB", estado: "Paraíba", genero: "f", nomeArco: "Isabele do Correnteza", numero: "8080" },
    { slug: "jonas-souza", nome: "Jonas Souza", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PB", estado: "Paraíba", genero: "m", nomeArco: "Jonas Souza", numero: "8000" },
    { slug: "giovanny-godoi", nome: "Giovanny Godoi", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PR", estado: "Paraná", genero: "m", nomeArco: "Giovanny Godoi", numero: "8080" },
    { slug: "julia-de-souza-marinho", nome: "Julia Marinho", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PR", estado: "Paraná", genero: "f", nomeArco: "Julia Marinho", numero: "8000" },
    { slug: "madu-silva", nome: "Madu Silva", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PE", estado: "Pernambuco", genero: "f", nomeArco: "Madu Silva", numero: "8000" },
    { slug: "matheus-do-mlb", nome: "Matheus do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PE", estado: "Pernambuco", genero: "m", nomeArco: "Matheus do MLB", numero: "8080" },
    { slug: "augusto-ferreira", nome: "Augusto Ferreira", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PI", estado: "Piauí", genero: "m", nomeArco: "Augusto Ferreira", numero: "8000" },
    { slug: "dara-neto", nome: "Dara Neto", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "PI", estado: "Piauí", genero: "f", nomeArco: "Dara Neto", numero: "8080" },
    { slug: "esteban-crescente", nome: "Esteban Crescente", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RJ", estado: "Rio de Janeiro", genero: "m", nomeArco: "Esteban Crescente", numero: "8000" },
    { slug: "petala", nome: "Pétala", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RJ", estado: "Rio de Janeiro", genero: "f", nomeArco: "Pétala", numero: "8080" },
    { slug: "bia-do-mlb", nome: "Bia do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RN", estado: "Rio Grande do Norte", genero: "f", nomeArco: "Bia do MLB", numero: "8000" },
    { slug: "victor-hugo", nome: "Victor Hugo", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RN", estado: "Rio Grande do Norte", genero: "m", nomeArco: "Victor Hugo", numero: "8080" },
    { slug: "bruno-do-mlb", nome: "Bruno do MLB", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RS", estado: "Rio Grande do Sul", genero: "m", nomeArco: "Bruno do MLB", numero: "8080" },
    { slug: "gustavo-ramos", nome: "Gustavo Ramos", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RS", estado: "Rio Grande do Sul", genero: "m", nomeArco: "Gustavo Ramos", numero: "8000" },
    { slug: "prof-jaque", nome: "Prof Jaque", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "RS", estado: "Rio Grande do Sul", genero: "f", nomeArco: "Prof Jaque", numero: "8008" },
    { slug: "amanda-wenceslau", nome: "Amanda Wenceslau", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SC", estado: "Santa Catarina", genero: "f", nomeArco: "Amanda Wenceslau", numero: "8000" },
    { slug: "andre-drejan", nome: "André Drejan", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SC", estado: "Santa Catarina", genero: "m", nomeArco: "André Drejan", numero: "8080" },
    { slug: "dany-oliveira", nome: "Dany Oliveira", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo", genero: "f", nomeArco: "Dany Oliveira", numero: "8080" },
    { slug: "karla-albuquerque", nome: "Karla Albuquerque", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo", genero: "f", nomeArco: "Karla Albuquerque", numero: "8008" },
    { slug: "matheus-morais", nome: "Matheus Morais", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo", genero: "m", nomeArco: "Matheus Morais", numero: "8001" },
    { slug: "ricardo-senese", nome: "Ricardo Senese", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo", genero: "m", nomeArco: "Ricardo Senese", numero: "8000" },
    { slug: "thais-gasparinj", nome: "Thais Gasparini", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SP", estado: "São Paulo", genero: "f", nomeArco: "Thais Gasparini", numero: "8010" },
    { slug: "bruna-makida", nome: "Bruna Makida", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SE", estado: "Sergipe", genero: "f", nomeArco: "Bruna Makida", numero: "8080" },
    { slug: "mateus-henriques", nome: "Mateus Henriques", cargo: "deputado-federal", cargoRotulo: "Deputado(a) Federal", uf: "SE", estado: "Sergipe", genero: "m", nomeArco: "Mateus Henriques", numero: "8000" },
    { slug: "daniel-calisto", nome: "Daniel Calisto", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "AL", estado: "Alagoas", genero: "m", nomeArco: "Daniel Calisto", numero: "80123" },
    { slug: "professora-maria-jose", nome: "Professora Maria José", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "AL", estado: "Alagoas", genero: "f", nomeArco: "Professora Maria José", numero: "80180" },
    { slug: "louise-ferreira", nome: "Louise Ferreira", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "BA", estado: "Bahia", genero: "f", nomeArco: "Louise Ferreira", numero: "80000" },
    { slug: "willian-santos", nome: "Willian Santos", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "BA", estado: "Bahia", genero: "m", nomeArco: "Willian Santos", numero: "80123" },
    { slug: "dianne-glebia", nome: "Dianne Glebia", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "CE", estado: "Ceará", genero: "f", nomeArco: "Dianne Glebia", numero: "80180" },
    { slug: "otavio-miranda", nome: "Otávio Miranda", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "CE", estado: "Ceará", genero: "m", nomeArco: "Otávio Miranda", numero: "80000" },
    { slug: "barbara-calista", nome: "Bárbara Calista", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "DF", estado: "Distrito Federal", genero: "f", nomeArco: "Bárbara Calista", numero: "80110" },
    { slug: "christian-sena", nome: "Christian Rodrigues Sena", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "DF", estado: "Distrito Federal", genero: "m", nomeArco: "Christian Rodrigues Sena", numero: "80123" },
    { slug: "larissa-moura", nome: "Larissa Moura", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "GO", estado: "Goiás", genero: "f", nomeArco: "Larissa Moura", numero: "80180" },
    { slug: "prof-pedro-augusto", nome: "Prof. Pedro Augusto", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "GO", estado: "Goiás", genero: "m", nomeArco: "Prof. Pedro Augusto", numero: "80000" },
    { slug: "daniel-tito", nome: "Daniel Tito", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "MG", estado: "Minas Gerais", genero: "m", nomeArco: "Daniel Tito", numero: "80123" },
    { slug: "candidatura-coletiva-contra-mineracao", nome: "Iris Raquel Contra a Mineração", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "MG", estado: "Minas Gerais", genero: "f", nomeArco: "Contra a Mineração", cargoArco: "Coletivo", numero: "80000" },
    { slug: "marcos-jobson", nome: "Marcos Jobson", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PA", estado: "Pará", genero: "m", nomeArco: "Marcos Jobson", numero: "80000" },
    { slug: "maria-santos", nome: "Maria Santos", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PA", estado: "Pará", genero: "f", nomeArco: "Maria Santos", numero: "80180" },
    { slug: "jozivan-antero", nome: "Jozivan Antero", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PB", estado: "Paraíba", genero: "m", nomeArco: "Jozivan Antero", numero: "80123" },
    { slug: "prof-cleber", nome: "Prof. Cleber", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PB", estado: "Paraíba", genero: "m", nomeArco: "Prof. Cleber", numero: "80800" },
    { slug: "vitoria-ohara", nome: "Vitoria Ohara", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PB", estado: "Paraíba", genero: "f", nomeArco: "Vitoria Ohara", numero: "80180" },
    { slug: "juliane-mendes", nome: "Juliane Mendes", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PR", estado: "Paraná", genero: "f", nomeArco: "Juliane Mendes", numero: "80000" },
    { slug: "lohan-cota", nome: "Lohan Cota", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PR", estado: "Paraná", genero: "m", nomeArco: "Lohan Cota", numero: "80080" },
    { slug: "jessica-nathalia", nome: "Jéssica Nathália", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PE", estado: "Pernambuco", genero: "f", nomeArco: "Jéssica Nathália", numero: "80180" },
    { slug: "paulo-fernando", nome: "Paulo Fernando", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "PE", estado: "Pernambuco", genero: "m", nomeArco: "Paulo Fernando", numero: "80680" },
    { slug: "bianca-rubim", nome: "Bianca Rubim", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro", genero: "f", nomeArco: "Bianca Rubim", numero: "80800" },
    { slug: "dulce", nome: "Dulce", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro", genero: "f", nomeArco: "Dulce", numero: "80456" },
    { slug: "eunice-do-mlb", nome: "Eunice do MLB", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro", genero: "f", nomeArco: "Eunice do MLB", numero: "80123" },
    { slug: "henderson", nome: "Henderson", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro", genero: "m", nomeArco: "Henderson", numero: "80000" },
    { slug: "monique-zuma", nome: "Monique Zuma", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro", genero: "f", nomeArco: "Monique Zuma", numero: "80180" },
    { slug: "ruan-vidal", nome: "Ruan Vidal", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RJ", estado: "Rio de Janeiro", genero: "m", nomeArco: "Ruan Vidal", numero: "80080" },
    { slug: "chapa-coletiva-fnr", nome: "Chapa Coletiva FNR", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RN", estado: "Rio Grande do Norte", genero: "coletivo", nomeArco: "Frente Negra Revolucionária", cargoArco: "", numero: "80000" },
    { slug: "milenne-barbosa", nome: "Milenne Barbosa", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RN", estado: "Rio Grande do Norte", genero: "f", nomeArco: "Milenne Barbosa", numero: "80180" },
    { slug: "everaldo", nome: "Everaldo Oliveira", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RS", estado: "Rio Grande do Sul", genero: "m", nomeArco: "Everaldo Oliveira", numero: "80000" },
    { slug: "samara", nome: "Samara Garcia", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "RS", estado: "Rio Grande do Sul", genero: "f", nomeArco: "Samara Garcia", numero: "80123" },
    { slug: "frente-operaria", nome: "Frente Operaria", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "SP", estado: "São Paulo", genero: "m", nomeArco: "Frente Operária", cargoArco: "", numero: "80123" },
    { slug: "julia-cachos", nome: "Julia Cachos", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "SP", estado: "São Paulo", genero: "f", nomeArco: "Julia Cachos", numero: "80000" },
    { slug: "giovanni-oliveira", nome: "Giovanni Oliveira", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "SE", estado: "Sergipe", genero: "m", nomeArco: "Giovanni Oliveira", numero: "80800" },
    { slug: "rose-mlb", nome: "Rose do MLB", cargo: "deputado-estadual", cargoRotulo: "Deputado(a) Estadual", uf: "SE", estado: "Sergipe", genero: "f", nomeArco: "Rose do MLB", numero: "80123" }
  ];

  // Ordem de exibição dos cargos nos seletores (não é ordem alfabética).
  var ORDEM_CARGOS = ["presidente", "governador", "senador", "deputado-federal", "deputado-estadual"];

  window.CANDIDATURAS = CANDIDATURAS;
  window.ORDEM_CARGOS = ORDEM_CARGOS;
  window.CANDIDATURA_PADRAO = "samara-martins";
})();
